# This is a basic workflow to help you get started with Actions

name: CI_CD-Pipeline-to-AWS
env: 
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask-application-packages" 
  EB_APPLICATION_NAME : "MyFlask" 
  EB_ENVIRONMENT_NAME : "MyFlask-env" 
  DEPLOY_PACKAGE_NAME : "flask_app_${{github.sha}}.zip"
  AWS_REGION_NAME     : "us-west-2" 
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
     -master
jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git clone 
      - uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Create zip deployment package 
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git* 
        
     
